<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TourType</name>
   <tag></tag>
   <elementGuidId>d9b4870c-68cb-408a-8ca2-b29c92708906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/div[@class=&quot;select2-result-label&quot;][contains(.,'${type}')]</value>
   </webElementProperties>
</WebElementEntity>
